<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>pi_stream_cam</RootNamespace>
        <AssemblyName>pi-stream-cam</AssemblyName>
        <LangVersion>default</LangVersion>
        <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>pi-stream-cam</PackageId>
        <Version>1.0.0</Version>
        <FileVersion>1.0.0.0</FileVersion>
        <InformationalVersion>1.0.0</InformationalVersion>
        <Company>Pi Stream Cam</Company>
        <Product>Pi Stream Cam</Product>
        <Description>PTZ Camera Surveillance System for Raspberry Pi</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Iot.Device.Bindings" Version="4.0.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\VERSION" Pack="true" PackagePath="\">
            <Link>VERSION</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
